server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  #Spring Cloud Stream配置
  cloud:
    stream:
      binders: #在此处配置要绑定的RabbitMQ的服务信息
        defaultRabbit: #表示定义的名称，用于与binding整合
          type: rabbit #消息中间件类型
          environment: #配置RabbitMQ的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: heartExchange #表示要使用的Exchange的名称定义
          content-type: application/json #设置消息类型，本次为json，文本则设置为text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

#Euraka客户端配置
eureka:
  client:
    register-with-eureka: true  #是否将自己注册进EurekaServer 默认为true
    fetch-registry: true  #是否从EurekaServer
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册到多台Eureka服务端实例，用逗号隔开
  instance:
    instance-id: receiver-8802.com #在信息列表时显示主机名称
    prefer-ip-address: true #访问的路径变为IP地址
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔，默认为30秒
    lease-expiration-duration-in-seconds: 5 #设置超时的时间间隔，默认为90秒