server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
#consul注册中心配置
  cloud:
    consul:
      host: 172.16.29.94
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        health-check-url: http://localhost:8006/actuator/health
        heartbeat:
          enabled: true
        prefer-ip-address: true