server:
  port: 9004

spring:
  application:
    name: cloud-payment-service-nacos
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://heartzz.com:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234566
  #Nacos作为服务注册中心的配置
  cloud:
    nacos:
      discovery:
        server-addr: heartzz.com:1111

#暴露监控的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.heart.springcloud.entities    # 所有Entity别名类所在包