server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order-service

eureka:
  client:
    register-with-eureka: false  #是否将自己注册进EurekaServer 默认为true  #是否从EurekaServer
    fetch-registry: true #是否从注册中心获取其它服务的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册到多台Eureka服务端实例，用逗号隔开

#开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

#ribbon超时设置
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000

#Hystrix默认超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000