server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order-service

eureka:
  client:
    register-with-eureka: false  #是否将自己注册进EurekaServer 默认为true  #是否从EurekaServer
    fetch-registry: true #是否从注册中心获取其它服务的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册到多台Eureka服务端实例，用逗号隔开
