server:
  port: 80

spring:
  application:
    name: cloud-order-service  #向EurekaServer注册服务时会取该属性作为服务中心里的服务名 很重要

#Eureka单机版配置
#eureka:
#  client:
#    register-with-eureka: true  #是否将自己注册进EurekaServer 默认为true
#    fetch-registry: true  #是否从EurekaServer
#    service-url:
#      defaultZone: http://localhost:7001/eureka #只注册到一台Eureka服务端实例
#  instance:
#    instance-id: order80
#    prefer-ip-address: true

#Eureka集群版版配置
eureka:
  client:
    register-with-eureka: false  #是否将自己注册进EurekaServer 默认为true  #是否从EurekaServer
    fetch-registry: true #是否从注册中心获取其它服务的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册到多台Eureka服务端实例，用逗号隔开
#  instance:
#    instance-id: order80
#    prefer-ip-address: true


#OpenFeign超时控制配置，由Ribbon实现，单位毫秒
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000
#加上这个配置后，再访问测试接口/consumer/payment/feign/timeout，就不会报错了

#OpenFeign日志打印级别配置
logging:
  level:
    #feign日志以什么级别监控那个接口
    com.heart.springcloud.service.FeignPaymentService: debug

