server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service

#Eureka单机版配置
#eureka:
#  client:
#    register-with-eureka: true  #是否将自己注册进EurekaServer 默认为true
#    fetch-registry: true  #是否从EurekaServer
#    service-url:
#      defaultZone: http://localhost:7001/eureka #只注册到一台Eureka服务端实例
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true

#Eureka集群版版配置
eureka:
  client:
    register-with-eureka: true  #是否将自己注册进EurekaServer 默认为true
    fetch-registry: true  #是否从EurekaServer
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册到多台Eureka服务端实例，用逗号隔开
  instance:
    instance-id: payment8001
    prefer-ip-address: true
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2