server:
  port: 85

spring:
  application:
    name: cloud-order-service-nacos
  cloud:
    #Nacos作为服务注册中心的配置
    nacos:
      discovery:
        server-addr: heartzz.com:1111
    #Sentinel作为服务监控中心
    sentinel:
      transport:
        dashboard: localhost:8080 #Sentinel dashboard地址
        port: 8719 #Sentinel api port, 默认8719, 被占用会依次+1去检测端口是否可用

#暴露监控的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#开启OpenFeign对Sentinel的支持
feign:
  sentinel:
    enabled: true
