server:
  port: 80

spring:
  application:
    name: consul-consumer-order
#consul注册中心配置
  cloud:
    consul:
      host: 172.16.29.94
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true
