server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
#SpringCloud Gateway网关路由配置
#  cloud:
#    gateway:
#      routes:
#        - id: payment_get #路由的ID，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/** #断言，路径相匹配的进行路由，加**通配符是因为实际接口上有一个@PathVariable注解接收动态参数
#
#        - id: payment_lb #路由的ID，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb #断言，路径相匹配的进行路由

#SpringCloud Gateway利用微服务名进行动态网关路由配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_get #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由，加**通配符是因为实际接口上有一个@PathVariable注解接收动态参数

        - id: payment_lb #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb #断言，路径相匹配的进行路由
            - After=2021-03-04T10:14:26.654+08:00[Asia/Shanghai] #断言，在指定日期之后的请求才能进行路由，否则都被拒绝访问

#Eureka集群版版配置
eureka:
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true  #是否将自己注册进EurekaServer 默认为true
    fetch-registry: true  #是否从EurekaServer
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册到多台Eureka服务端实例，用逗号隔开
